### ISSUE TITLE
本書籍の前著に対する位置付け

### ISSUE THREAD

**Issue by tealgreen0503** [shibuiwilliam/building-ml-system#4]
本書籍の[前著](https://www.shoeisha.co.jp/book/detail/9784798169453)に対する位置付けは以下のうちどちらに当てはまるでしょうか？

1. 前著を読了していることを前提としており、本書籍を読む前に前著を読むことを推奨している。
2. 本書籍は前著の内容を包含しており、本書籍を読むために前著を読むことは必須ではない。
3. 前著と本書籍は全く異なる位置付けの書籍である。

お手隙の際にご回答いただけますと幸いです。
よろしくお願い致します。

**Comment by shibuiwilliam** [comment]
@tealgreen0503 
ご質問ありがとうございます。
3.が近いですが、前著を読まなくても本書を理解する問題はないですが、前著を読んでおいたほうが本書の理解は深まると思います。
前著は方法論で、本書は実践という位置づけです。

**Comment by tealgreen0503** [comment]
@shibuiwilliam 
ご回答いただきありがとうございます！
位置付けについて理解しました。前著から読ませていただきます。

**Comment by shibuiwilliam** [comment]
@tealgreen0503 
ありがとうございます！
